# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddf2599b3bc213552f5d97425e0267647e54cf8088f8cbc8151d22eb88e0f874d26749607725820182f8c7367759c1a540ddad191452d5af56cc0075ce451b2f

test:
  secret_key_base: 7992013897e52bf4f49073a34cf8452437f3156bf886db99424ab6609faf2a9e183a72c0178d09d80465f4847d06c6e18b9c50dec35ac5d4659353968b2956fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
